### PR TITLE
updated container setup.

### PR DESCRIPTION
**Pull request by mbien**
- fixed urls
 - upgraded to jdk17 and latest lib versions
 - better signal handling (made sure container stop signal propagates to tomcat)

i leave this as draft until we have a tag for 6.1, so i can change the git checkout line.

### CODE REVIEW

**Comment by mbien** [comment]
@snoopdave could we get a roller-6.1.0 tag for the recent release?

**Comment by snoopdave** [comment]
@mbien I pushed a roller-6.1.0 tag today and cleaned up all the old RC tags.

**Review by snoopdave — APPROVED** [review]
LGTM

**Comment by mbien** [comment]
perfect. I changed the containerfile to checkout tags/roller-6.1.0 instead of master.

**Pull request merged**
