### PR TITLE
search index compatibility and other minor changes

### PR DESCRIPTION
**Pull request by mbien**
I set this pull request against 6.0.x since master had bugs and was lacking behind last time I tried (see https://github.com/apache/roller/pull/58#issuecomment-616370669).

contents:
- better lucene search index compatibility. Point release updates won't trigger index rebuilds
- updated project dependencies to latest releases (skipped spring and webjars)
- removed double synchronization in cache
- tested on 11, 14 and 15b26

### CODE REVIEW

**Comment by mbien** [comment]
oops, forgot that this pull request was still open. seems like github is automatically adding new commits to PRs.

**Comment by snoopdave** [comment]
Sorry I missed this one @mbien. I'll take a look this week.

**Comment by mbien** [comment]
No worries @snoopdave. The last commit should probably be in a separate PR for spring changes.

**Comment by snoopdave** [comment]
Hi @mbien. Thanks for this work. Since this PR updates Spring security, I would like to test it with and LDAP setup to ensure we don't break blogs.apache.org, which uses LDAP. I hope to get to this in the next week or so.

**Comment by mbien** [comment]
@snoopdave like i mentioned before the spring commit should not be part of this PR, it was my mistake since i didn't expect github to add new commits to existing PRs without asking. I have more spring related changes waiting locally and would put them into a different branch since i agree those would require more testing.

Unfortunately github does not seem to provide the option to cherry pick commits from a PR, so the simplest solution would probably be me pushing the branch again with --force without the last commit. This shouldn't break this PR (i hope).

**Comment by gmazza** [comment]
@mbien For the type of changes you're making, you may wish to take a look at my "TightBlog" fork of Roller (https://github.com/gmazza/tightblog), it's only about one-third the size of Roller today so you may find it a much more cleaned-out and solid product to build on.

**Comment by mbien** [comment]
@gmazza nice I didn't know about tightblog. I would have checked it out this winter before I casually started updating roller if i would have known about it earlier. 

But most items i wanted to work on are finished now so i am fairly happy where its at (for my needs). Size isn't a big issue, i am running Roller (from my repo) and 3 other JVMs on a 1gb raspi model and it is doing ok. Startup is slow but that is to be expected on that hardware. But good to know that there are alternatives.

**Review by snoopdave — APPROVED** [review]
Looks good!

**Comment by mbien** [comment]
> Looks good!

@snoopdave thanks. Let me know if there is anything else to do for me so that this PR can be merged.

**Comment by snoopdave** [comment]
Go for it. I think it’s ready

**Comment by mbien** [comment]
@snoopdave perfect - but I have no merge button, all I can do is to comment :)

**Comment by snoopdave** [comment]
well, dang. @mbien I'm not sure why you cannot merge. I will look into that this weekend. Thanks for putting this together.

**Comment by adityasharma7** [comment]
Hi @mbien,

It seems you are still not in roller committers.

Have you configured the account with the below setup?
https://git.apache.org/setup/

Note: You are required to enable 2FA on GitHub before you can gain write-access to repositories

**Comment by mbien** [comment]
> Hi @mbien,
> 
> It seems you are still not in roller committers.
> 
> Have you configured the account with the below setup?
> https://git.apache.org/setup/
> 
> Note: You are required to enable 2FA on GitHub before you can gain write-access to repositories

2FA is always on + i can see myself on this page:
https://github.com/orgs/apache/teams/apache-committers/members?query=mbien

tbh i don't really need a merge button since someone with write rights has to review the PRs anyway - i gladly delegate the button pressing to someone else :)

**Pull request merged**
