### PR TITLE
Translation: Simplified Chinese

### PR DESCRIPTION
**Pull request by silkriver**
Made a full translation of simplified Chinese

### CODE REVIEW

**Comment by mbien** [comment]
hello @silkriver. 
Thank you for the translation. However before you can contribute to an Apache project you would have to sign the Apache contributor agreement (ICLA) found here: 
https://www.apache.org/licenses/contributor-agreements.html#clas
and submit it to Apache via email
https://www.apache.org/licenses/contributor-agreements.html#submitting

after that I can merge your contribution.

**Comment by silkriver** [comment]
OK, I have send the documents.

**Comment by mbien** [comment]
@silkriver unfortunately i still see the same email address

```
git fetch origin pull/100/head:chinese_local
git checkout chinese_local
git log
commit 793d5e2d60afdae1e953d222724d050ccae7cf70 (HEAD -> chinese_local)
Author: silkriver <yuqinju@163.com>
Date:   Sun Jul 18 19:37:06 2021 +0800

    Translation: Simplified Chinese
...
```

could you try:
`git commit --amend --author="Luo Cheng <yuqinju@hotmail.com>"`
and force push again?

**Comment by silkriver** [comment]
@mbien ok I tried again.

**Comment by mbien** [comment]
excellent, i see the matching author information now.

@silkriver thank you for the contribution and patience. The next PR should be easier :)

**Pull request merged**
