### PR TITLE
Removed: the type specification from right side when using generics

### PR DESCRIPTION
**Pull request by ymaheshwari1**
Removed type specification from the planet pojos package

### CODE REVIEW

**Comment by mbien** [comment]
hi @ymaheshwari1,
are you planing to do this for more packages? Project wide "Inspect and Transform" using netbeans gives me over 150 hits for "can use diamond". I noticed you did something similar recently in #77. Maybe we can aggregate more in this PR, otherwise this won't ever end :)

feel free to set this PR to draft if you planing to add more so that it isn't integrated before its done.

**Comment by ymaheshwari1** [comment]
> hi @ymaheshwari1,
> are you planing to do this for more packages? Project wide "Inspect and Transform" using netbeans gives me over 150 hits for "can use diamond". I noticed you did something similar recently in #77. Maybe we can aggregate more in this PR, otherwise this won't ever end :)
> 
> feel free to set this PR to draft if you planing to add more so that it isn't integrated before its done.

Sure, I will convert the PR to draft and will update the same in other packages as well.

**Comment by adityasharma7** [comment]
Hi @ymaheshwari1 
Is it done?

**Comment by ymaheshwari1** [comment]
> Hi @ymaheshwari1
> Is it done?

Hi,
Some of the packages are yet to be updated, I will complete them as soon as possible.

**Comment by ymaheshwari1** [comment]
> Hi @ymaheshwari1
> Is it done?

Hi,
I have removed all the type specifications please review.

**Comment by mbien** [comment]
@ymaheshwari1 excellent, thank you. Changes look good.

If @snoopdave is ok with this i would like integrate this PR. Should we squash all 21 commits to one or leave it as is with a simple merge?

**Comment by snoopdave** [comment]
@mbien looks good. Usually, I prefer to squash but I don't have a strong opinion.

**Comment by mbien** [comment]
squashed + merged. thank you for the contribution @ymaheshwari1

**Pull request merged**
