### PR TITLE
[ROL-2123] make Roller build and run on Java 11

### PR DESCRIPTION
**Pull request by snoopdave**
WIP do not merge. More testing is necessary.

Tests are now passing and Roller seems to work fine under Java 11.

### CODE REVIEW

**Comment by snoopdave** [comment]
There appears to be a problem with Guice under Java 11. Tests fail with this exception when Maven compiler plugin is set to 11.

``` 123   │ 1) Error injecting constructor, org.apache.roller.weblogger.WebloggerException
 124   │   at org.apache.roller.weblogger.business.jpa.JPAPersistenceStrategy.<init>(JPAPersistenceStrategy.java:67)
 125   │   at org.apache.roller.weblogger.business.jpa.JPAWebloggerModule.configure(JPAWebloggerModule.java:66)
 126   │   while locating org.apache.roller.weblogger.business.jpa.JPAPersistenceStrategy
 127   │     for the 1st parameter of org.apache.roller.weblogger.business.jpa.JPAWebloggerImpl.<init>(JPAWebloggerImpl.java:70)
 128   │   at org.apache.roller.weblogger.business.jpa.JPAWebloggerImpl.class(JPAWebloggerImpl.java:70)
 129   │   while locating org.apache.roller.weblogger.business.jpa.JPAWebloggerImpl
 130   │   while locating org.apache.roller.weblogger.business.Weblogger
 131   │
 132   │ 1 error
 133   │        at org.apache.roller.weblogger.business.jpa.JPAPersistenceStrategy.<init>(JPAPersistenceStrategy.java:108)
 134   │        at org.apache.roller.weblogger.business.jpa.JPAPersistenceStrategy$$FastClassByGuice$$4bf11a60.newInstance(<generated>)
 135   │        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
 136   │        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
 137   │        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
 138   │        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
 139   │        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
 140   │        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
 141   │        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
```

**Comment by mbien** [comment]
i investigated a little and tried to find the issue but ran out of time.
 - double checked that ASM 7.0 and latest Guice is in use and nothing else, by dumping the classpath in the unit test (everything seemed fine)
 - tested with a nightly build of ASM with same result

As mentioned before, compiling with language level set to 10 while building/testing/running on Java 11 works just fine.

I wished the Guice exception msg would be a bit more helpful ;) The next step i wanted to take would have been to try to reproduce it in a small test to figure out if its guice, asm or specific to the way roller uses the injections - but at this point i ran out of time.

**Comment by shamshad95** [comment]
Update

**Comment by mbien** [comment]
updated most* dependencies which didn't require code changes + added explicit dependency to ASM to get better control of what version is used.

tests are now green on AdoptOpenJDK 12.01, 11.03 and 1.8u212 using language levels 12, 11 and 1.8.

https://github.com/mbien/roller/commit/07b51df0b7e1abebd41c1af1816217ea7c123eb3

*i couldn't update javax.persistence to jakarta.persistence because the API seems to be signed while the eclipselink impl isn't which leads to a security exception during classloading. Old JPA 2.1.1 isn't signed so the CL does not complain.

**Comment by mbien** [comment]
fixed the eclipselink dependency issue. Changed 'eclipselink' artifact to 'org.eclipse.persistence.jpa' + removed old 'javax.persistence' dependency.
https://github.com/mbien/roller/commit/d284c76ef5c4a9bea190939d5a4bef06703dae48

the dependency tree looks now slightly different but all jars are signed correctly and don't cause sec ex during classloading.
'
[INFO] +- org.eclipse.persistence:org.eclipse.persistence.jpa:jar:2.7.4:compile
[INFO] |  +- org.eclipse.persistence:jakarta.persistence:jar:2.2.2:compile
[INFO] |  +- org.eclipse.persistence:org.eclipse.persistence.asm:jar:2.7.4:compile
[INFO] |  +- org.eclipse.persistence:org.eclipse.persistence.antlr:jar:2.7.4:compile
[INFO] |  +- org.eclipse.persistence:org.eclipse.persistence.jpa.jpql:jar:2.7.4:compile
[INFO] |  \- org.eclipse.persistence:org.eclipse.persistence.core:jar:2.7.4:compile
[INFO] |     \- (org.eclipse.persistence:org.eclipse.persistence.asm:jar:2.7.4:compile - omitted for duplicate)
'

**Comment by snoopdave** [comment]
@mbien awesome, thanks so much! I made the same changes locally and all tests pass, plus Roller is up and running on Java 11.  

Do you want to submit this as a PR against my java11 branch so you get credit? I'm not sure when the team will want to merge this to master, but I'm hoping Roller 6 can be on Java 11.

**Comment by mbien** [comment]
@snoopdave done: https://github.com/apache/roller/pull/25

(btw I am running roller on a Raspberry Pi 3 on JDK 12 right now - works great)

**Pull request merged**
