### PR TITLE
Added github actions for basic build/test setup.

### PR DESCRIPTION
**Pull request by mbien**
- builds/tests on JDK 11 and 17
- uploads junit report
- disabled a failing test for now

### CODE REVIEW

**Comment by mbien** [comment]
i think the junit report will start working once the yaml is in master.
should look like this: https://github.com/mbien/roller/runs/4631232068?check_suite_focus=true
and if something fails:
https://github.com/mbien/roller/runs/4631155838?check_suite_focus=true

**Comment by mbien** [comment]
added step for selenium tests (didn't know that geckodriver could run headless).

**Review by snoopdave — APPROVED** [review]
This looks very cool. I have not tried it out yet, but I see no reason not to merge.

**Comment by mbien** [comment]
awesome. I merge it, lets see if everything builds.

**Comment by mbien** [comment]
it builds and tests but it didn't upload the test report (it should appear on the list on the left i think)
https://github.com/apache/roller/actions/runs/1627718913

Don't know why because I tested it on my wip branch and it worked fine. (but its not so important tbh, the full log is recorded anyway in case something fails)

**Comment by mbien** [comment]
oh haha. It published it in he CodeQL action
https://github.com/apache/roller/actions/runs/1627718912

**Comment by mbien** [comment]
https://github.com/mikepenz/action-junit-report/issues/40

**Pull request merged**
